services:
  be:
    build:
      context: ./backend
      target: run-prod
    volumes:
      - ./backend/server.py:/backend/server.py
    image: be

  prod-client:
    build:
      context: ./prod-frontend
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - be
